# Generated by Django 4.1.4 on 2022-12-16 19:05

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
